# mongo -u root -p rootpassword
version: '3.7'
services:
  mongodb_container:
    image: mongo:4.2.22
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${VARIABLE:-root}"
      MONGO_INITDB_ROOT_PASSWORD: "${VARIABLE:-rootpassword}"
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  server:
    image: chaitanyavootla/tmb:latest
    profiles:
      - prod
    pull_policy: always
    ports:
      - 3000:3000

volumes:
  mongodb:
