version: '3.7'
services:
  mongodb_container:
    image: mongo:5.0.12
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${VARIABLE:-root}"
      MONGO_INITDB_ROOT_PASSWORD: "${VARIABLE:-rootpassword}"
    volumes:
      - mongodb:/data/db
  server:
    image: chaitanyavootla/tmb:latest
    profiles:
      - prod
    ports:
      - 3000:3000

volumes:
  mongodb:
