---
description: UI component patterns and shadcn/ui usage guidelines
globs: ["src/components/**/*.tsx"]
alwaysApply: false
---

# Component Development Rules

## shadcn/ui Usage

### DO NOT modify files in `src/components/ui/`

These are generated by shadcn CLI. To customize:

1. Override styles with Tailwind classes when using the component
2. Create wrapper components in `src/components/features/`
3. Use CSS variables for theming

### Using shadcn Components

```tsx
// ✅ GOOD: Use className for customization
import { Button } from "@/components/ui/button";
<Button className="bg-brand-primary hover:bg-brand-primary/90">Watch Now</Button>;

// ❌ BAD: Modifying the Button component file
```

## Feature Components

### Location

Place domain-specific components in `src/components/features/{domain}/`:

```
src/components/features/
├── movie/
│   ├── movie-card.tsx
│   ├── movie-card-actions.tsx
│   ├── movie-carousel.tsx
│   ├── hero-carousel.tsx      # Landing page hero (uses MediaBackdrop + HeroContent)
│   └── media-logo.tsx
├── media/                      # Shared movie/series detail components
│   ├── index.ts               # Export hub for all media components
│   ├── hero-content.tsx        # Shared hero content layout (logo, meta, genres, ratings)
│   ├── media-hero.tsx          # Details page hero (uses MediaBackdrop + HeroContent)
│   ├── media-backdrop.tsx      # Prime Video-style backdrop (image right, black left)
│   ├── media-overview.tsx      # Overview, cast carousel, details sidebar
│   ├── media-actions.tsx       # Play, watchlist, favorite buttons
│   ├── media-scroller.tsx      # Reusable horizontal scroll section
│   ├── genre-badge.tsx         # Genre list component
│   ├── ratings-bar.tsx         # Multi-source ratings (TMDB, IMDb, RT, Google)
│   ├── image-gallery.tsx       # Gallery with full-screen lightbox modal
│   ├── video-gallery.tsx       # YouTube video player with sidebar
│   ├── collection-section.tsx  # Movie collection (franchise) scroller
│   ├── recommendations-section.tsx  # Recommended & Similar scrollers
│   ├── keywords-list.tsx       # Clickable keyword badges
│   ├── country-language-badges.tsx  # Country flags and language
│   ├── content-warning-link.tsx     # Parental guidance link
│   └── watch-options.tsx            # Streaming providers pill (compact)
├── discover/                   # Browse/filter components
│   ├── index.ts               # Export hub
│   ├── filter-sidebar.tsx     # Main filter panel (genres, rating, language, etc.)
│   ├── discover-grid.tsx      # Infinite scroll grid of results
│   ├── discover-scroller.tsx  # Horizontal scroller for topic previews
│   ├── media-type-toggle.tsx  # Movies/Series toggle
│   ├── sort-select.tsx        # Sort dropdown (popularity, rating, date)
│   ├── genre-filter.tsx       # Genre chips (compact + horizontal scroll variants)
│   ├── multi-select-combobox.tsx  # Searchable multi-select (exclude genres)
│   └── searchable-select.tsx  # Searchable single-select (language, country)
├── series/
│   ├── index.ts               # Export hub for series components
│   ├── season-selector.tsx    # Season dropdown with episode count/date
│   ├── episode-scroller.tsx   # Horizontal episode cards scroller
│   ├── episode-sheet.tsx      # Episode detail sheet with image gallery
│   └── next-episode-card.tsx  # Upcoming/latest episode card
├── person/
│   ├── index.ts               # Export hub for person components
│   ├── person-hero.tsx        # Profile photo, bio, external links
│   ├── person-filmography.tsx # Credits by decade with MovieCard scrollers
│   ├── person-card.tsx        # Card for cast sections (+ compact variant)
│   └── person-images.tsx      # Photo gallery with lightbox
├── auth/
│   ├── index.ts               # Export hub for auth components
│   ├── google-one-tap.tsx     # Google One Tap prompt (non-invasive)
│   ├── login-dialog.tsx       # Manual sign-in modal
│   └── user-menu.tsx          # Avatar dropdown (profile, settings, logout)
├── layout/
│   ├── nav-bar.tsx            # Includes admin + watchlist links, country selector
│   ├── footer.tsx
│   ├── theme-toggle.tsx
│   └── country-selector.tsx   # Country selection for watch providers
└── providers/
    ├── index.tsx              # Main providers wrapper (auth, theme, query, etc.)
    └── user-store-provider.tsx # Hydrates user store on auth changes
```

### Hero Section Architecture

The hero sections use a **composable architecture** with shared components:

```
┌─────────────────────────────────────────────────────────────┐
│ HeroCarousel (landing page)    │ MediaHero (detail pages)   │
├─────────────────────────────────────────────────────────────┤
│                    MediaBackdrop                            │
│  (handles backdrop image positioning, gradients, overlays)  │
├─────────────────────────────────────────────────────────────┤
│                     HeroContent                             │
│  (handles logo, meta, genres, ratings, actions layout)      │
└─────────────────────────────────────────────────────────────┘
```

#### Shared Components

**`MediaBackdrop`** - Prime Video-style backdrop:
- Image positioned to the right: `left-0 md:left-[20%] lg:left-[25%]`
- Black background base for clean left side
- Gradient fade from black on image's left edge (200-300px)
- Three overlay presets: `light`, `medium`, `heavy`

**`HeroContent`** - Content layout:
- Logo → meta (year, runtime/seasons) → genres → rating → actions
- Shared animation variants (`heroContainerVariants`, `heroItemVariants`)
- Accepts custom `actions` prop for different button configurations

```tsx
import { MediaBackdrop } from "@/components/features/media";
import { HeroContent } from "@/components/features/media";

// In MediaHero (detail pages)
<MediaBackdrop item={item} mediaType={mediaType} overlay="light">
  <HeroContent
    itemId={item.id}
    title={title}
    mediaType={mediaType}
    ratings={item.ratings}
    watchOptions={item.watch_options}
    watchProviders={item.watch_providers}
    actions={<MediaActions ... />}
  />
</MediaBackdrop>

// In HeroCarousel (landing page) - uses heroEnhancedData from getTrending()
<HeroCarousel
  items={trending.allItems}
  heroEnhancedData={trending.heroEnhancedData}  // Ratings + watch options per item
/>

// HeroCarousel internally passes enhanced data to HeroContent:
<HeroContent
  itemId={currentItem.id}
  title={title}
  mediaType={mediaType}
  ratings={enhancedData?.ratings}              // Multi-source ratings
  watchOptions={enhancedData?.watchOptions}    // Pre-processed for country
  watchProviders={enhancedData?.watchProviders} // For country switching
  googleData={enhancedData?.googleData}        // Scraped data (India)
  item={currentItem}
/>
```

#### Design Specs

- **Height**: `min-h-[50vh] md:min-h-[55vh] lg:min-h-[60vh]`
- **Content positioning**: `items-end` with bottom padding
- **HeroCarousel**: Fully clickable (navigates to detail page)
- **Action buttons**: Glassmorphism style (`bg-white/10 hover:bg-white/20 backdrop-blur-sm`)

### RatingsBar Component

Unified ratings display showing scores from multiple sources (TMDB, IMDb, Rotten Tomatoes, Google).

```tsx
import { RatingsBar } from "@/components/features/media";

// Basic usage with ratings from movie/series
<RatingsBar ratings={movie.ratings} size="md" />

// Fallback to TMDB-only when no external ratings
<RatingsBar
  ratings={movie.ratings?.length
    ? movie.ratings
    : [{ name: "TMDB", rating: Math.round(movie.vote_average * 10).toString() }]
  }
/>
```

**Design principles:**
- Single grouped pill container (not separate pills per source)
- Ratings separated by subtle `border-white/15` dividers
- Icon + color-coded score for each source
- Muted color palette: `hsl(h, 50%, 55%)` for scores
- Sizes: `sm` (cards), `md` (hero), `lg` (detail sections)

**Vertical alignment pattern:**
```tsx
// Use fixed-height wrapper for icons to ensure alignment
<div className={cn("relative flex-shrink-0", heightClass)} style={{ width: iconSize }}>
  <Image src={icon} fill className="object-contain" unoptimized />
</div>
```

**Rating sources (in order):**
1. TMDB - Always shown first
2. IMDb - From MongoDB external_data
3. Rotten Tomatoes (Critic) - With certified/rotten variants
4. Rotten Tomatoes (Audience) - With certified/rotten variants
5. Google - From MongoDB googleData

### WatchOptions Component

Compact pill showing streaming providers for a movie/series:

```tsx
import { WatchOptions } from "@/components/features/media";

<WatchOptions
  watchOptions={item.watch_options}           // Pre-processed for user's country
  watchProviders={item.watch_providers}       // Raw TMDB data for country switching
  googleData={googleData}                     // Scraped data (India only)
  item={{ id, title, poster_path, backdrop_path, images }}
  isMovie={true}
/>
```

**Design specs:**
- Compact pill design with glassmorphism (`bg-black/30 backdrop-blur-sm`)
- Provider icons at 24x24px with tooltips for details
- Shows "Watch (IN)" indicator when using fallback country
- Max 5 providers visible, expand button for more

**Data flow:**
1. Server pre-processes watch options using `getWatchOptionsForCountry()`
2. Server also sends optimized `watch_providers` (filtered to ~15 countries)
3. Client re-processes on-the-fly when user changes country via `CountrySelector`
4. For JustWatch links (TMDB), opens Google search instead of broken deep links

**Integration in HeroContent:**
```tsx
// HeroContent receives watch props and renders WatchOptions after RatingsBar
<HeroContent
  watchOptions={watch_options}
  watchProviders={optimized_watch_providers}
  googleData={googleData}
  item={item}
  // ... other props
/>
```

### CountrySelector Component

Dropdown for selecting watch provider region:

```tsx
import { CountrySelector } from "@/components/features/layout";

// In NavBar
<CountrySelector />

// Compact mode (flag only)
<CountrySelector compact />
```

**Features:**
- Uses `country-list` library for complete country list (250+ countries)
- Priority countries (IN, US, UK, CA, AU, DE, FR, JP) shown at top
- Searchable with flag icons from `flagcdn.com`
- Stores selection in `countryOverride` (Zustand user store)
- Client-side only (not persisted to server)

**Design specs:**
- Button: Flag icon + country code (e.g., 🇮🇳 IN)
- Popover: 260px wide, 300px scroll area
- Search input at top for filtering

### Media Detail Page Patterns

#### Card Sizes in Scrollers

Consistent card widths across scrollable sections:

```tsx
// Standard poster cards (recommendations, similar, collection)
className="w-[130px] sm:w-[145px] md:w-[160px] flex-shrink-0"

// Cast cards (slightly smaller)
className="w-[110px] sm:w-[125px] md:w-[140px] flex-shrink-0"

// Gallery image thumbnails
style={{ height: "120px", width: `${aspectRatio * 120}px` }}
```

#### Full-Screen Modals (Custom vs shadcn Dialog)

For full-screen lightbox/gallery modals, use **custom fixed overlay** instead of shadcn Dialog:

```tsx
// ✅ GOOD: Custom full-screen overlay (works reliably)
{isOpen && (
  <div className="fixed inset-0 z-50 bg-black">
    <Button onClick={handleClose} className="absolute right-4 top-4 z-50">
      <X />
    </Button>
    {/* Content */}
  </div>
)}

// ❌ AVOID: shadcn Dialog for full-screen modals (styling issues)
<Dialog open={isOpen}>
  <DialogContent className="max-w-[100vw] h-screen">
```

Remember to prevent body scroll:

```tsx
useEffect(() => {
  if (isOpen) {
    document.body.style.overflow = "hidden";
  } else {
    document.body.style.overflow = "";
  }
  return () => { document.body.style.overflow = ""; };
}, [isOpen]);
```

#### Video Gallery Height Sync

Sync sidebar scroll area height with main player:

```tsx
const mainPlayerRef = useRef<HTMLDivElement>(null);
const [playerHeight, setPlayerHeight] = useState(0);

useEffect(() => {
  const updateHeight = () => {
    if (mainPlayerRef.current) {
      setPlayerHeight(mainPlayerRef.current.offsetHeight);
    }
  };
  updateHeight();
  window.addEventListener("resize", updateHeight);
  return () => window.removeEventListener("resize", updateHeight);
}, []);

// Use in sidebar
<ScrollArea style={{ height: `${playerHeight + 60}px` }}>
```

#### Inline Video Playback

Videos should play in-place, not in modals:

```tsx
const [isPlaying, setIsPlaying] = useState(false);

{isPlaying ? (
  <iframe
    src={`https://www.youtube-nocookie.com/embed/${videoKey}?autoplay=1&rel=0`}
    allow="accelerometer; autoplay; clipboard-write; encrypted-media"
    allowFullScreen
    className="absolute inset-0 w-full h-full"
  />
) : (
  <>
    <Image src={thumbnailUrl} fill />
    <button onClick={() => setIsPlaying(true)}>
      <Play />
    </button>
  </>
)}
```

### Series-Specific Components

#### Season Selector Pattern

The `SeasonSelector` manages season selection and episode loading:

```tsx
import { SeasonSelector } from "@/components/features/series";

<SeasonSelector
  seriesId={series.id}
  seriesName={series.name}
  seasons={series.seasons}
  className="mt-6"
/>
```

Features:
- Dropdown for season selection (defaults to latest season)
- Displays episode count and air date
- Lazy loads episodes via `getSeason()` server action
- Shows loading skeleton while fetching

#### Episode Cards

Episode cards in scrollers follow a consistent pattern:

```tsx
// Episode card dimensions (aspect-video thumbnails)
className="w-[240px] md:w-[280px] flex-shrink-0"

// Episode thumbnail
<div className="relative aspect-video rounded-lg overflow-hidden bg-muted">
  <Image
    src={`https://image.tmdb.org/t/p/w400${episode.still_path}`}
    alt={episode.name}
    fill
    className="object-cover"
    sizes="280px"
  />
  {/* Rating badge */}
  <Badge className="absolute top-2 right-2 bg-black/70">
    {episode.vote_average.toFixed(1)}
  </Badge>
  {/* Runtime badge */}
  <Badge className="absolute bottom-2 right-2 bg-black/70">
    {episode.runtime}m
  </Badge>
</div>
```

#### Episode Sheet with Image Gallery

The `EpisodeSheet` fetches full episode details on open:

```tsx
<EpisodeSheet
  episode={selectedEpisode}
  seriesId={seriesId}
  seriesName={seriesName}
  seasonNumber={seasonNumber}
  onClose={() => setSelectedEpisode(null)}
/>
```

Features:
- Fetches detailed episode data via `getEpisode()` action
- Image gallery with multiple stills from TMDB
- Thumbnail strip navigation
- Full-screen lightbox with keyboard nav (←/→, Esc)
- Director/writer credits with person links
- Guest stars carousel

#### Next/Last Episode Card

Show upcoming or latest episode info:

```tsx
import { EpisodeInfoSection } from "@/components/features/series";

<EpisodeInfoSection
  nextEpisode={series.next_episode_to_air}
  lastEpisode={series.last_episode_to_air}
  seriesName={series.name}
  className="mt-8"
/>
```

Displays:
- Episode still, title, season/episode number
- Air date with "days until/since" indicator
- Runtime and overview
- Status badges: Upcoming (yellow), Next (green), Last (blue)

#### Series Status Badge

Enhanced status badge with visual states:

```tsx
function SeriesStatusBadge({ status, inProduction, nextAirDate }) {
  // Returns appropriate color/label based on status:
  // - "Airing" (emerald + pulsing dot) - has upcoming episode
  // - "Ongoing" / "Returning Soon" (green)
  // - "Ended" (slate)
  // - "Canceled" (red)
  // - "In Production" (yellow)
  // - "Pilot" (purple)
  // - "Planned" (blue)
}
```

### Person-Specific Components

#### Person Page Structure

The person page follows this layout:
1. **PersonHero** - Profile photo, name, bio, meta info, social links
2. **Known For** - Top credits by popularity (MediaScroller + MovieCard)
3. **PersonImages** - Photo gallery with lightbox
4. **PersonFilmography** - Full filmography grouped by decade

#### PersonHero Spacing

Person pages need extra top padding since there's no backdrop:

```tsx
// PersonHero uses more top padding to clear navbar
<div className="px-4 md:px-8 lg:px-12 pt-16 md:pt-20 pb-8 md:pb-12">
```

#### PersonFilmography Pattern

Filmography uses `MovieCard` in `MediaScroller` for visual consistency:

```tsx
import { PersonFilmography } from "@/components/features/person";

<PersonFilmography person={person} className="mt-8" />
```

Features:
- **Tabs**: Movies / TV Shows with counts
- **Filter**: Acting / Crew / All Credits
- **Browse All link**: Links to `/browse` with cast/crew filter for the person
- **Grouped by decade**: 2020s, 2010s, 2000s, etc.
- **Uses MovieCard**: Same visual style as recommendations
- **No truncation**: Shows all credits (with posters)

```tsx
// Decade scrollers structure
<MediaScroller title="2020s">
  {credits.map((credit) => (
    <MovieCard
      item={creditToListItem(credit)}
      className="w-[130px] sm:w-[145px] md:w-[160px] flex-shrink-0"
    />
  ))}
</MediaScroller>
```

#### PersonCard for Cast Sections

Use `PersonCard` in cast carousels for linking to person pages:

```tsx
import { PersonCard } from "@/components/features/person";

// In cast scrollers
{cast.map((member) => (
  <PersonCard
    key={member.id}
    person={member}
    size="md" // or "sm"
    className="flex-shrink-0"
  />
))}
```

Card sizes:
- `size="md"` (default): `w-20 md:w-24`, `h-28 md:h-36`
- `size="sm"`: `w-16`, `h-24`

#### PersonImages Gallery

Photo gallery with lightbox viewer:

```tsx
import { PersonImages } from "@/components/features/person";

{profileImages.length > 1 && (
  <PersonImages
    images={profileImages}
    personName={person.name}
    className="mt-8"
  />
)}
```

Features:
- Horizontal scroll thumbnails
- Click to open lightbox
- Keyboard navigation (←/→, Esc)
- Thumbnail strip in lightbox

#### Credit to ListItem Conversion

When using `MovieCard` with person credits, convert to list item format:

```tsx
function creditToListItem(credit: PersonCombinedCastCredit): MovieListItem | SeriesListItem {
  if (credit.media_type === "movie") {
    return {
      id: credit.id,
      title: credit.title || "",
      poster_path: credit.poster_path,
      backdrop_path: credit.backdrop_path,
      vote_average: credit.vote_average,
      vote_count: credit.vote_count,
      release_date: credit.release_date || "",
      genre_ids: credit.genre_ids,
      overview: credit.overview,
      popularity: credit.popularity,
      adult: credit.adult,
      media_type: "movie",
    };
  }
  // Similar for TV...
}
```

### Discover Components

#### FilterSidebar

The main filter panel for browse page, uses collapsible sections:

```tsx
import { FilterSidebar } from "@/components/features/discover";

<FilterSidebar
  params={params}
  onChange={handleParamsChange}
  hideMediaToggle  // When toggle is in header instead
  hideSort         // When sort is in header instead
/>
```

**Sections:**
- Genres (GenreFilterCompact - chips that wrap)
- Minimum Rating (Select)
- Minimum Votes (Select)
- Language (SearchableSelect - searchable dropdown)
- Country of Origin (SearchableSelect)
- Exclude Genres (MultiSelectCombobox - searchable multi-select)

#### DiscoverGrid

Infinite scroll grid with intersection observer:

```tsx
import { DiscoverGrid } from "@/components/features/discover";

<DiscoverGrid
  initialResults={results}
  totalPages={totalPages}
  totalResults={totalResults}
  params={params}
  showCount={false}     // Header shows count
  infiniteScroll        // Enable infinite scroll
/>
```

**Grid sizing (optimized for poster resolution):**
```tsx
className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 lg:grid-cols-6 xl:grid-cols-7 gap-2.5 md:gap-3"
```

#### DiscoverScroller

Horizontal scroller for topic previews (topics index page):

```tsx
import { DiscoverScroller } from "@/components/features/discover";
import { buildBrowseUrl } from "@/lib/discover";

// Link to topic detail page
<DiscoverScroller
  title="Action Movies"
  seeAllHref="/topics/genre-action-movie"
  initialResults={previewResults}
  params={{ media_type: "movie", with_genres: [28] }}
/>

// Link to browse with filters
<DiscoverScroller
  title="Tom Cruise Movies"
  seeAllHref={buildBrowseUrl({ media_type: "movie", with_cast: [500] })}
  seeAllLabel="Browse All"
  initialResults={previewResults}
  params={{ media_type: "movie", with_cast: [500] }}
/>
```

**Card sizing in scrollers:**
```tsx
className="w-[120px] sm:w-[135px] md:w-[150px] lg:w-[160px]"
```

#### Scroller "See All" Link Pattern

All scrollers (`MovieCarousel`, `MediaScroller`, `DiscoverScroller`) use a uniform link pattern:

```tsx
// Props available on all scrollers:
seeAllHref?: string;    // URL for "View All" link
seeAllLabel?: string;   // Custom label (default: "View All")

// Uniform link styling
<Link
  href={seeAllHref}
  className="inline-flex items-center gap-1 text-sm text-brand hover:text-brand/80"
>
  {seeAllLabel}
  <ArrowRight className="h-3.5 w-3.5" />
</Link>
```

Usage examples:
- **Home page carousels**: Link to browse with `sort_by: "popularity.desc"`
- **Topic scrollers**: Link to topic detail page (`/topics/{key}`)
- **Person filmography**: Link to browse with cast/crew filter
- **Topic detail page**: "Customize" button links to browse with topic filters

#### SearchableSelect & MultiSelectCombobox

Searchable dropdown components using shadcn Command:

```tsx
import { SearchableSelect, MultiSelectCombobox } from "@/components/features/discover";

// Single select with search (language, country)
<SearchableSelect
  options={languageOptions}
  value={params.with_original_language}
  onChange={(val) => handleChange({ with_original_language: val })}
  placeholder="Any language"
  clearable
/>

// Multi-select with search (exclude genres)
<MultiSelectCombobox
  options={genreOptions}
  selected={params.without_genres || []}
  onChange={(genres) => handleChange({ without_genres: genres })}
  placeholder="Select genres to exclude..."
  maxDisplay={3}  // Show 3 badges, then "+N more"
/>
```

#### Active Filter Pills

Display selected filters as closable pills in the header:

```tsx
// Pattern for filter pills
{selectedGenreNames.map((name, idx) => (
  <Badge key={idx} variant="secondary" className="gap-1 pr-1">
    {name}
    <button onClick={() => removeGenre(selectedGenres[idx])}>
      <X className="h-3 w-3" />
    </button>
  </Badge>
))}

{activeFilterCount > 1 && (
  <Button variant="ghost" size="sm" onClick={clearAllFilters}>
    Clear all
  </Button>
)}
```

### Component Structure

```tsx
// src/components/features/movie/movie-card.tsx
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import type { Movie } from "@/types";

interface MovieCardProps {
  movie: Movie;
  className?: string;
  showRating?: boolean;
}

export function MovieCard({ movie, className, showRating = true }: MovieCardProps) {
  return (
    <Card className={cn("group cursor-pointer transition-all", className)}>
      {/* Implementation */}
    </Card>
  );
}
```

## Image Handling

### CDN Image Pattern

Use the CDN (`image.themoviebrowser.com`) as primary source with TMDB fallback:

```tsx
// src/lib/image.ts utilities
import { getPosterSources, getBackdropSources, getLogoUrl } from "@/lib/image";

// Get sources with CDN primary, TMDB fallback
const posterSources = getPosterSources(item, "movie");
// { primary: "https://image.themoviebrowser.com/movie/123/poster.webp",
//   fallback: "https://image.tmdb.org/t/p/w500/path.jpg" }
```

### CDN URL Structure

```
https://image.themoviebrowser.com/{movie|series}/{id}/{type}.webp

Types:
- poster    → Movie/series poster
- backdrop  → Background image
- logo      → Title logo (transparent)
- widePoster → Wide format poster
```

### Image Component Pattern

```tsx
"use client";

import { useState } from "react";
import Image from "next/image";
import { getPosterSources } from "@/lib/image";

export function MoviePoster({ item, mediaType }: Props) {
  const [useFallback, setUseFallback] = useState(false);
  const sources = getPosterSources(item, mediaType);

  const src = useFallback ? sources.fallback : sources.primary;

  return (
    <Image
      src={src}
      alt={`${item.title} poster`}
      fill
      onError={() => {
        if (!useFallback && sources.fallback) {
          setUseFallback(true);
        }
      }}
      unoptimized={!useFallback} // CDN images already optimized
    />
  );
}
```

### MediaLogo Component

For movie/series logos with 3-tier fallback:

```tsx
import { MediaLogo } from "@/components/features/movie/media-logo";

// Fallback chain: CDN logo → TMDB logo → Text
// CDN URL: https://image.themoviebrowser.com/{movie|series}/{id}/logo.webp
<MediaLogo
  item={{ id: 123, title: "Movie Title" }}
  mediaType="movie"
  // tmdbLogoPath is OPTIONAL - only pass if you already have it
  // The component tries CDN first, which covers most cases
  tmdbLogoPath={logoPath}
  fallbackText="Movie Title"
  maxWidth={400}
  maxHeight={120}
/>

// Typical usage (no tmdbLogoPath - relies on CDN → text fallback)
<MediaLogo
  item={{ id: movie.id, title: movie.title }}
  mediaType="movie"
  fallbackText={movie.title}
/>
```

**Performance note:** Don't fetch TMDB images just to get a logo path.
The CDN should have logos for popular content. Let it fall back to text for rare cases.

### Image Types (src/lib/image.ts)

```typescript
export enum ImageType {
  POSTER = "poster",
  LOGO = "logo",
  BACKDROP = "backdrop",
  WIDE_CARD = "widePoster",
}

// Helper functions
getPosterSources(item, mediaType)   // Returns { primary, fallback }
getBackdropSources(item, mediaType) // Returns { primary, fallback }
getLogoUrl(item, mediaType)         // Returns CDN logo URL
getTmdbLogoUrl(logoPath, size)      // Returns TMDB logo URL
```

### TMDB Image Resolutions

Use appropriate TMDB image sizes for different contexts:

```tsx
const TMDB_IMAGE_BASE = "https://image.tmdb.org/t/p";

// Gallery/Lightbox main image - original resolution
`${TMDB_IMAGE_BASE}/original${filePath}`

// Gallery scroll thumbnails - medium quality
`${TMDB_IMAGE_BASE}/w500${filePath}`

// Lightbox thumbnail strip - low resolution
`${TMDB_IMAGE_BASE}/w185${filePath}`

// YouTube thumbnails (external)
`https://img.youtube.com/vi/${videoKey}/maxresdefault.jpg` // Main player
`https://img.youtube.com/vi/${videoKey}/mqdefault.jpg`     // Thumbnails
```

For external images (TMDB, YouTube), use `unoptimized` prop or native `<img>`:

```tsx
// ✅ Using Next.js Image with unoptimized
<Image src={tmdbUrl} unoptimized fill />

// ✅ Using native img for lightbox (avoids Next.js optimization overhead)
<img src={`${TMDB_IMAGE_BASE}/original${path}`} className="max-w-full max-h-full" />
```

## Component Patterns

### 1. Composition over Configuration

```tsx
// ✅ GOOD: Composable
<Card>
  <CardHeader>
    <CardTitle>{movie.title}</CardTitle>
  </CardHeader>
  <CardContent>
    <MoviePoster src={movie.posterPath} />
  </CardContent>
</Card>

// ❌ BAD: Over-configured
<MovieCard
  title={movie.title}
  poster={movie.posterPath}
  showHeader={true}
  headerStyle="default"
/>
```

### 2. Client/Server Split

```tsx
// movie-card.tsx (Server Component by default)
import { MovieCardActions } from "./movie-card-actions";

export function MovieCard({ movie }: { movie: Movie }) {
  return (
    <Card>
      <MoviePoster movie={movie} />
      <MovieCardActions movieId={movie.id} /> {/* Client boundary */}
    </Card>
  );
}

// movie-card-actions.tsx (Client Component)
"use client";

export function MovieCardActions({ movieId }: { movieId: number }) {
  const { toggleWatchlist } = useUserStore();
  return <Button onClick={() => toggleWatchlist(movieId)}>Add</Button>;
}
```

### 3. State Reset with Keys

When component state should reset on prop changes, use React keys:

```tsx
// ✅ GOOD: Key-based state reset
function MediaLogo({ item, ...props }) {
  return (
    <MediaLogoInner
      key={item.id} // Resets internal state when item changes
      {...props}
    />
  );
}

// ❌ BAD: useEffect to reset state (causes cascading renders)
useEffect(() => {
  setLoadState("cdn");
}, [item.id]);
```

### 4. Loading States

Always provide skeleton states for async content:

```tsx
import { Skeleton } from "@/components/ui/skeleton";

export function MovieCardSkeleton() {
  return (
    <Card>
      <Skeleton className="aspect-[2/3] w-full rounded-lg" />
      <Skeleton className="h-4 w-3/4 mt-2" />
    </Card>
  );
}
```

## Animation Guidelines

### Framer Motion Usage

```tsx
"use client";
import { motion } from "framer-motion";

// Simple hover effects
<motion.div
  whileHover={{ scale: 1.02 }}
  whileTap={{ scale: 0.98 }}
  transition={{ duration: 0.2 }}
>
  <MovieCard movie={movie} />
</motion.div>

// Page transitions (in layout)
<motion.main
  initial={{ opacity: 0, y: 20 }}
  animate={{ opacity: 1, y: 0 }}
  exit={{ opacity: 0 }}
>
  {children}
</motion.main>
```

### CSS-First for Simple Animations

```tsx
// Use Tailwind for simple hover/focus states
<Card className="transition-all duration-300 hover:scale-[1.02] hover:shadow-xl">
```

## Watchlist Page Pattern

The watchlist page uses a tabbed interface with different layouts for movies and series:

```
src/app/watchlist/
├── page.tsx    # Server component with metadata
└── client.tsx  # Client component with tabs, data fetching
```

### Layout Guidelines

- **Full width**: No max-width container (matches browse page)
- **No header**: Remove redundant page titles to save vertical space
- **Default tab**: TV Shows first (more actionable with airing schedules)
- **Tab alignment**: Left-aligned with `w-fit` (not centered)

```tsx
// page.tsx
export default function WatchlistPage() {
  return (
    <main className="min-h-screen pt-16 pb-12 px-4 md:px-6 lg:px-8">
      <Suspense fallback={<WatchlistSkeleton />}>
        <WatchlistClient />
      </Suspense>
    </main>
  );
}
```

### Series Categorization

Watchlisted series are categorized by status for better UX:

```typescript
interface CategorizedSeries {
  currentlyAiring: Series[];  // Has next_episode_to_air
  returning: Series[];        // Status: "Returning Series", "In Production", "Planned"
  completed: Series[];        // Status: "Ended", "Canceled" or no upcoming
  totalCount: number;
}
```

Display each category in a `MediaScroller` with status badges:
- **Currently Airing**: Green pulsing dot + "Airing" badge
- **Returning**: Blue calendar icon + "Coming Back" badge
- **Completed**: Gray clock icon + "Ended" badge

### Movies Grid

Movies display in a responsive grid (same as browse):

```tsx
<div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 lg:grid-cols-6 xl:grid-cols-7 2xl:grid-cols-8 gap-2.5 md:gap-3">
  {movies.map((movie) => (
    <MovieCard key={movie.id} item={movie} />
  ))}
</div>
```

### Data Fetching

Use TanStack Query for client-side data fetching with optimistic hydration:

```tsx
const { data: watchlist, isLoading } = useQuery({
  queryKey: ["watchlist"],
  queryFn: () => fetch("/api/user/watchlist").then(r => r.json()),
  enabled: authStatus === "authenticated",
  staleTime: 30000,
});
```

## Accessibility Requirements

1. All interactive elements need proper ARIA labels
2. Images need descriptive alt text
3. Color contrast must meet WCAG AA
4. Focus states must be visible
5. Use semantic HTML elements

```tsx
<Button aria-label={`Add ${movie.title} to watchlist`}>
  <Plus className="h-4 w-4" />
</Button>

<Image
  alt={`${movie.title} movie poster - ${movie.year}`}
  src={posterUrl}
/>
```

## Hydration Safety

### Avoid Non-Deterministic Rendering

Formatting functions that differ between server/client will cause hydration errors:

```tsx
// ❌ BAD: Intl.NumberFormat can differ between Node.js and browser
const formatCurrency = (amount: number) => {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    notation: "compact",
    maximumFractionDigits: 1,
  }).format(amount);
};

// ✅ GOOD: Deterministic formatting
const formatCurrency = (amount?: number): string | null => {
  if (!amount) return null;
  if (amount >= 1_000_000_000) {
    const billions = amount / 1_000_000_000;
    return `$${billions % 1 === 0 ? billions.toFixed(0) : billions.toFixed(1)}B`;
  }
  if (amount >= 1_000_000) {
    const millions = amount / 1_000_000;
    return `$${millions % 1 === 0 ? millions.toFixed(0) : millions.toFixed(1)}M`;
  }
  return `$${amount}`;
};
```

### Other Hydration Pitfalls

- `Date.now()`, `Math.random()` - use stable values
- `typeof window !== 'undefined'` branches - render same content on server
- Locale-dependent formatting - use explicit locale or deterministic code

## Personalized Homepage Sections

### Component Structure

```
src/components/features/
├── home/
│   ├── index.ts
│   └── personalized-sections.tsx  # Client component for auth-gated content
└── media/
    ├── wide-card.tsx              # Wide backdrop card for recents
    ├── wide-carousel.tsx          # Horizontal scroller for wide cards
    └── recent-tracker.tsx         # Invisible tracking component
```

### PersonalizedSections Component

Client component that shows Continue Watching and Recent Visits for authenticated users:

```tsx
// src/components/features/home/personalized-sections.tsx
"use client";

export function PersonalizedSections() {
  const { status } = useSession();
  const isHydrated = useUserStore(selectIsHydrated);
  const continueWatching = useUserStore(selectContinueWatching);
  const recents = useUserStore(selectRecents);

  // Don't render for unauthenticated users
  if (status !== "authenticated") return null;
  
  // Show loading while hydrating
  if (!isHydrated) return <WideCarousel loading ... />;
  
  // Don't render if no data
  if (continueWatching.length === 0 && recents.length === 0) return null;

  return (
    <>
      {continueWatching.length > 0 && (
        <WideCarousel title="Continue Watching" items={continueWatching} showWatchLinks />
      )}
      {recents.length > 0 && (
        <WideCarousel title="Recent Visits" items={recents} />
      )}
    </>
  );
}
```

### Homepage Order

Trending content comes first, personalized sections follow:

```tsx
// src/app/page.tsx
<div className="px-4 md:px-8 lg:px-12 pb-16 space-y-12">
  {/* 1. Trending Movies */}
  <MovieCarousel title="Trending Movies" items={trending.movies} />
  
  {/* 2. Trending TV Shows */}
  <MovieCarousel title="Trending TV Shows" items={trending.tv} />
  
  {/* 3. Personalized Sections (Continue Watching, Recents) */}
  <PersonalizedSections />
</div>
```

### WideCard Component

Wide backdrop card for recents and continue watching:

```tsx
// src/components/features/media/wide-card.tsx
interface WideCardProps {
  item: RecentItem | ContinueWatchingItem;
  className?: string;
  showWatchLink?: boolean;  // Show external link icon + provider logo
}

// Card dimensions: aspect-video (16:9)
// Width: w-[280px] sm:w-[320px] md:w-[380px]
// Image sources: CDN first (widePoster.webp), TMDB fallback
```

**Key behaviors:**
- No play icon on hover for recents (clean hover with subtle scale)
- External link icon only for continue watching items
- Defensive `isMovie` handling with title/name fallback

### RecentTracker Component

Invisible component that tracks page views:

```tsx
// src/components/features/media/recent-tracker.tsx
interface RecentTrackerProps {
  itemId: number;
  isMovie: boolean;
  title?: string;       // For movies
  name?: string;        // For series
  poster_path?: string | null;
  backdrop_path?: string | null;
}

// Usage in movie/series detail pages:
<RecentTracker
  itemId={movie.id}
  isMovie={true}
  title={movie.title}
  poster_path={movie.poster_path}
  backdrop_path={movie.backdrop_path}
/>
```

**Behavior:**
- Only tracks for authenticated users
- Fires once per page mount (with 500ms delay for hydration)
- Syncs to server via `/api/user/recents` (fire and forget)
