name: Nuxt Test

on:
    push:
        branches: [nuxt]

jobs:
    Build_Frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set Node.js 18
              uses: actions/setup-node@v2
              with:
                node-version: '18'
            - name: NPM intall
              timeout-minutes: 2
              run: |
                cd nuxt
                touch .env
                npm install
            - name: Nuxt Build
              timeout-minutes: 2
              run: |
                npm run build
