name: Nuxt Test

on:
  push:
    branches: [nuxt]

jobs:
  Deploy:
      runs-on: ubuntu-latest
      steps:
          - uses: appleboy/ssh-action@master
            with:
              host: 64.227.132.75
              username: root
              password: ${{ secrets.DIGITAL_OCEAN_PASS }}
              script: |
                  cd /beta/movie-browser
                  git checkout -f nuxt
                  git pull origin nuxt
                  nvm use default
                  npm install
                  npm run build
                  pm2 delete all
                  pm2 start "npm run preview" --name Nuxt
