name: Nuxt Test

on:
  push:
    branches: [nuxt]

jobs:
  Deploy:
      runs-on: ubuntu-latest
      steps:
          - uses: appleboy/ssh-action@master
            with:
              host: 134.209.159.54
              username: root
              password: ${{ secrets.DIGITAL_OCEAN_PASS }}
              script: |
                  cd /movie-browser
                  git pull origin nuxt
                  npm install
                  npm run build
                  sudo kill -9 `sudo lsof -t -i:3000`
                  export AUTH_ORIGIN=http://134.209.159.54 && nohup npm run preview &
