name: Build and Deploy Nuxt Project

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # specify your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Archive build files
      run: tar -czvf build.tar.gz .output .nuxt

    - name: Copy build to remote
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: root
        password: ${{ secrets.DIGITAL_OCEAN_PASS }}
        source: "build.tar.gz"
        target: "/beta/movie-browser"

    - name: Deploy on remote
      uses: appleboy/ssh-action@master
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      with:
        host: ${{ secrets.HOST }}
        username: root
        password: ${{ secrets.DIGITAL_OCEAN_PASS }}
        envs: DB_USER,DB_PASSWORD
        script: |
          source /root/.nvm/nvm.sh
          cd /beta/movie-browser
          git checkout -f master
          git pull origin master
          tar -xzvf build.tar.gz
          export DB_USER=${DB_USER}
          export DB_PASSWORD=${DB_PASSWORD}
          docker-compose up -d
          pm2 delete all
          pm2 start ecosystem.config.cjs
