name: Deploy

on:
  push:
    branches: [v2]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js to 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup
        timeout-minutes: 2
        run: |
          pushd client
          npm install
      - name: Build
        timeout-minutes: 2
        run: |
          pushd client
          npm run build
